### ISSUE TITLE
Google login

### ISSUE THREAD

**Issue by mohammadaaqib** [StephenGrider/AdvancedNodeStarter#9]
I am getting this error 
`GooglePlusAPIError: Legacy People API has not been used in project 70265989829 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=70265989829 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
    at D:\stell Project\AdvancedNodeStarter\node_modules\passport-google-oauth20\lib\strategy.js:95:21
    at passBackControl (D:\stell Project\AdvancedNodeStarter\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\stell Project\AdvancedNodeStarter\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by mohammadaaqib** [comment]
fixed this error by updating 
`"passport-google-oauth20": "^1.0.0",`
to 
`"passport-google-oauth20": "^2.0.0",`
